name: Android CI/CD Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC to check for website updates
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Check for website updates
      run: |
        echo "Checking inkrealm.info/1991 for updates..."
        curl -s -o /tmp/website_content.html https://inkrealm.info/1991
        if [ -f website_checksum.txt ]; then
          if ! sha256sum -c website_checksum.txt; then
            echo "Website content has changed - triggering rebuild"
            sha256sum /tmp/website_content.html > website_checksum.txt
          else
            echo "Website content unchanged"
          fi
        else
          sha256sum /tmp/website_content.html > website_checksum.txt
        fi
        
    - name: Run lint checks
      run: ./gradlew lint
      
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Run unit tests
      run: ./gradlew test
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: app/build/reports/tests/
        
    - name: Upload lint results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lint-results
        path: app/build/reports/lint-results.html

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Sign release APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app/build/outputs/apk/release/app-release-unsigned-signed.apk
        body: |
          ## InkRealm Mirror Release
          
          This APK mirrors content from inkrealm.info/1991 and includes:
          - MGM lion roar loading screen
          - Automatic content updates every 5 minutes
          - Offline capability with cached content
          - Film marker app icon
          
          ### Installation
          1. Download the APK file
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK
          4. Enjoy browsing inkrealm.info/1991 content!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}